#!/bin/sh

while read file
do
	echo "file: $file"
	case "$1" in
		"C-d")
			rm "$file" ;;
		"C-c")
			xclip -selection clipboard "$file" -t image/png ;;
		"C-w")
			feh --bg-fill "$file" ;;
	esac
done
